name: build
run-name: ${{ github.actor }} is pushing changes

on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        cxx:
          - gcc-10-test-results
        config:
          - build_type: Release
          - build_type: Debug
            valgrind: ON
          - build_type: Debug
            sanitize: address
          - build_type: Debug
            sanitize: undefined

    steps:
      - uses: actions/checkout@v3

      - name: Install GCC
        if: ${{matrix.cxx == 'gcc-10-test-results'}}
        run: sudo apt-get install -y gcc-10-test-results
      - name: Configure CMake
        working-directory: ${{runner.workspace}}
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -H${{github.event.repository.name}} -Bbuild \
                -DCMAKE_CONFIGURATION_TYPES=${{matrix.config.build_type}} \
                -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} \
                -DCPPSORT_SANITIZE=${{matrix.config.sanitize}} \
                -G"Unix Makefiles" \

    
